export const LANGUAGES = [
  ['ab', 'Abkhaz'],
  ['ace', 'Acehnese'],
  ['ach', 'Acholi'],
  ['aa', 'Afar'],
  ['af', 'Afrikaans'],
  ['sq', 'Albanian'],
  ['alz', 'Alur'],
  ['am', 'Amharic'],
  ['ar', 'Arabic'],
  ['hy', 'Armenian'],
  ['as', 'Assamese'],
  ['av', 'Avar'],
  ['awa', 'Awadhi'],
  ['ay', 'Aymara'],
  ['az', 'Azerbaijani'],
  ['ban', 'Balinese'],
  ['bal', 'Baluchi'],
  ['bm', 'Bambara'],
  ['bci', 'Baoulé'],
  ['ba', 'Bashkir'],
  ['eu', 'Basque'],
  ['btx', 'Batak Karo'],
  ['bts', 'Batak Simalungun'],
  ['bbc', 'Batak Toba'],
  ['be', 'Belarusian'],
  ['bem', 'Bemba'],
  ['bn', 'Bengali'],
  ['bew', 'Betawi'],
  ['bho', 'Bhojpuri'],
  ['bik', 'Bikol'],
  ['bs', 'Bosnian'],
  ['br', 'Breton'],
  ['bg', 'Bulgarian'],
  ['bua', 'Buryat'],
  ['yue', 'Cantonese'],
  ['ca', 'Catalan'],
  ['ceb', 'Cebuano'],
  ['ch', 'Chamorro'],
  ['ce', 'Chechen'],
  ['ny', 'Chichewa'],
  ['zh-Hans', 'Chinese (Simplified)'],
  ['zh-Hant', 'Chinese (Traditional)'],
  ['chk', 'Chuukese'],
  ['cv', 'Chuvash'],
  ['co', 'Corsican'],
  ['crh-Cyrl', 'Crimean Tatar (Cyrillic)'],
  ['crh-Latn', 'Crimean Tatar (Latin)'],
  ['hr', 'Croatian'],
  ['cs', 'Czech'],
  ['da', 'Danish'],
  ['prs', 'Dari'],
  ['dv', 'Dhivehi'],
  ['din', 'Dinka'],
  ['doi', 'Dogri'],
  ['dov', 'Dombe'],
  ['nl', 'Dutch'],
  ['nl-BE', 'Flemish (Belgian Dutch)'],
  ['dyu', 'Dyula'],
  ['dz', 'Dzongkha'],
  ['en', 'English'],
  ['eo', 'Esperanto'],
  ['et', 'Estonian'],
  ['ee', 'Ewe'],
  ['fo', 'Faroese'],
  ['fj', 'Fijian'],
  ['fil', 'Filipino'],
  ['fi', 'Finnish'],
  ['fon', 'Fon'],
  ['fr', 'French'],
  ['fr-CA', 'French (Canada)'],
  ['fy', 'Frisian'],
  ['fur', 'Friulian'],
  ['ff', 'Fulani'],
  ['gaa', 'Ga'],
  ['gl', 'Galician'],
  ['ka', 'Georgian'],
  ['de', 'German'],
  ['el', 'Greek'],
  ['gn', 'Guarani'],
  ['gu', 'Gujarati'],
  ['ht', 'Haitian Creole'],
  ['cnh', 'Hakha Chin'],
  ['ha', 'Hausa'],
  ['haw', 'Hawaiian'],
  ['he', 'Hebrew'],
  ['hil', 'Hiligaynon'],
  ['hi', 'Hindi'],
  ['hmn', 'Hmong'],
  ['hu', 'Hungarian'],
  ['hrx', 'Hunsrik'],
  ['iba', 'Iban'],
  ['is', 'Icelandic'],
  ['ig', 'Igbo'],
  ['ilo', 'Ilocano'],
  ['id', 'Indonesian'],
  ['iu-Latn', 'Inuktut (Latin)'],
  ['iu-Cans', 'Inuktut (Syllabics)'],
  ['ga', 'Irish'],
  ['it', 'Italian'],
  ['jam', 'Jamaican Patois'],
  ['ja', 'Japanese'],
  ['jv', 'Javanese'],
  ['kac', 'Jingpo'],
  ['kl', 'Kalaallisut'],
  ['kn', 'Kannada'],
  ['kr', 'Kanuri'],
  ['pam', 'Kapampangan'],
  ['kk', 'Kazakh'],
  ['kha', 'Khasi'],
  ['km', 'Khmer'],
  ['cgg', 'Kiga'],
  ['kg', 'Kikongo'],
  ['rw', 'Kinyarwanda'],
  ['ktu', 'Kituba'],
  ['trp', 'Kokborok'],
  ['kv', 'Komi'],
  ['gom', 'Konkani'],
  ['ko', 'Korean'],
  ['kri', 'Krio'],
  ['ku', 'Kurdish (Kurmanji)'],
  ['ckb', 'Kurdish (Sorani)'],
  ['ky', 'Kyrgyz'],
  ['lo', 'Lao'],
  ['ltg', 'Latgalian'],
  ['la', 'Latin'],
  ['lv', 'Latvian'],
  ['lij', 'Ligurian'],
  ['li', 'Limburgish'],
  ['ln', 'Lingala'],
  ['lt', 'Lithuanian'],
  ['lmo', 'Lombard'],
  ['lg', 'Luganda'],
  ['luo', 'Luo'],
  ['lb', 'Luxembourgish'],
  ['mk', 'Macedonian'],
  ['mad', 'Madurese'],
  ['mai', 'Maithili'],
  ['mak', 'Makassar'],
  ['mg', 'Malagasy'],
  ['ms', 'Malay'],
  ['ms-Arab', 'Malay (Jawi)'],
  ['ml', 'Malayalam'],
  ['mt', 'Maltese'],
  ['mam', 'Mam'],
  ['gv', 'Manx'],
  ['mi', 'Maori'],
  ['mr', 'Marathi'],
  ['mh', 'Marshallese'],
  ['mwr', 'Marwadi'],
  ['mfe', 'Mauritian Creole'],
  ['mhr', 'Meadow Mari'],
  ['mni-Mtei', 'Meiteilon (Manipuri)'],
  ['min', 'Minang'],
  ['lus', 'Mizo'],
  ['mn', 'Mongolian'],
  ['my', 'Myanmar (Burmese)'],
  ['nhe', 'Nahuatl (Eastern Huasteca)'],
  ['ndc', 'Ndau'],
  ['nr', 'Ndebele (South)'],
  ['new', 'Nepalbhasa (Newari)'],
  ['ne', 'Nepali'],
  ['nqo', 'NKo'],
  ['no', 'Norwegian'],
  ['nb', 'Norwegian Bokmål'],
  ['nus', 'Nuer'],
  ['oc', 'Occitan'],
  ['or', 'Odia (Oriya)'],
  ['om', 'Oromo'],
  ['os', 'Ossetian'],
  ['pag', 'Pangasinan'],
  ['pap', 'Papiamento'],
  ['ps', 'Pashto'],
  ['fa', 'Persian'],
  ['pl', 'Polish'],
  ['pt-BR', 'Portuguese (Brazil)'],
  ['pt-PT', 'Portuguese (Portugal)'],
  ['pa', 'Punjabi (Gurmukhi)'],
  ['pa-Arab', 'Punjabi (Shahmukhi)'],
  ['qu', 'Quechua'],
  ['kek', 'Qʼeqchiʼ'],
  ['rom', 'Romani'],
  ['ro', 'Romanian'],
  ['rn', 'Rundi'],
  ['ru', 'Russian'],
  ['se', 'Sami (North)'],
  ['sm', 'Samoan'],
  ['sg', 'Sango'],
  ['sa', 'Sanskrit'],
  ['sat-Latn', 'Santali (Latin)'],
  ['sat-Olck', 'Santali (Ol Chiki)'],
  ['gd', 'Scots Gaelic'],
  ['nso', 'Sepedi'],
  ['sr', 'Serbian'],
  ['st', 'Sesotho'],
  ['crs', 'Seychellois Creole'],
  ['shn', 'Shan'],
  ['sn', 'Shona'],
  ['scn', 'Sicilian'],
  ['szl', 'Silesian'],
  ['sd', 'Sindhi'],
  ['si', 'Sinhala'],
  ['sk', 'Slovak'],
  ['sl', 'Slovenian'],
  ['so', 'Somali'],
  ['es', 'Spanish'],
  ['su', 'Sundanese'],
  ['sus', 'Susu'],
  ['sw', 'Swahili'],
  ['ss', 'Swati'],
  ['sv', 'Swedish'],
  ['ty', 'Tahitian'],
  ['tg', 'Tajik'],
  ['tzm', 'Tamazight'],
  ['zgh', 'Tamazight (Tifinagh)'],
  ['ta', 'Tamil'],
  ['tt', 'Tatar'],
  ['te', 'Telugu'],
  ['tet', 'Tetum'],
  ['th', 'Thai'],
  ['bo', 'Tibetan'],
  ['ti', 'Tigrinya'],
  ['tiv', 'Tiv'],
  ['tpi', 'Tok Pisin'],
  ['to', 'Tongan'],
  ['lua', 'Tshiluba'],
  ['ts', 'Tsonga'],
  ['tn', 'Tswana'],
  ['tcy', 'Tulu'],
  ['tum', 'Tumbuka'],
  ['tr', 'Turkish'],
  ['tk', 'Turkmen'],
  ['tyv', 'Tuvan'],
  ['tw', 'Twi'],
  ['udm', 'Udmurt'],
  ['uk', 'Ukrainian'],
  ['ur', 'Urdu'],
  ['ug', 'Uyghur'],
  ['uz', 'Uzbek'],
  ['ve', 'Venda'],
  ['vec', 'Venetian'],
  ['vi', 'Vietnamese'],
  ['war', 'Waray'],
  ['cy', 'Welsh'],
  ['wo', 'Wolof'],
  ['xh', 'Xhosa'],
  ['sah', 'Yakut'],
  ['yi', 'Yiddish'],
  ['yo', 'Yoruba'],
  ['yua', 'Yucatec Maya'],
  ['zap', 'Zapotec'],
  ['zu', 'Zulu'],
];

export const SUPPORTED_LANGUAGES = new Set(LANGUAGES.map(([code]) => code));

// Gemini 3.5 Live Translate voice-to-voice subset (BCP-47). Other catalog
// entries are accepted end-to-end but the provider may reject them until
// Google expands Live Translate coverage.
export const GEMINI_LIVE_TRANSLATE_SUPPORTED = new Set([
  'af', 'ak', 'sq', 'am', 'ar', 'hy', 'az', 'eu', 'be', 'bn', 'bg', 'my', 'ca',
  'zh-Hans', 'zh-Hant', 'hr', 'cs', 'da', 'nl', 'en', 'et', 'fil', 'fi', 'fr',
  'gl', 'ka', 'de', 'el', 'gu', 'ha', 'he', 'hi', 'hu', 'is', 'id', 'it', 'ja',
  'jv', 'kn', 'kk', 'km', 'rw', 'ko', 'lo', 'lv', 'lt', 'mk', 'ms', 'ml', 'mr',
  'mn', 'ne', 'no', 'nb', 'fa', 'pl', 'pt-BR', 'pt-PT', 'pa', 'ro', 'ru', 'sr',
  'sd', 'si', 'sk', 'sl', 'es', 'su', 'sw', 'sv', 'ta', 'te', 'th', 'tr', 'uk',
  'ur', 'uz', 'vi', 'zu',
]);

const LOWER_TO_CANONICAL = new Map([...SUPPORTED_LANGUAGES].map(code => [code.toLowerCase(), code]));

// Common aliases (user input, legacy codes, region variants).
for (const [alias, canonical] of [
  ['tl', 'fil'],
  ['tagalog', 'fil'],
  ['iw', 'he'],
  ['jw', 'jv'],
  ['zh', 'zh-Hans'],
  ['zh-cn', 'zh-Hans'],
  ['zh-sg', 'zh-Hans'],
  ['zh-tw', 'zh-Hant'],
  ['zh-hk', 'zh-Hant'],
  ['pt', 'pt-BR'],
  ['fa-af', 'prs'],
  ['crh', 'crh-Latn'],
  ['sat', 'sat-Latn'],
  ['chm', 'mhr'],
  ['ku-iq', 'ckb'],
]) {
  if (!LOWER_TO_CANONICAL.has(alias)) LOWER_TO_CANONICAL.set(alias, canonical);
}

export function normalizeLanguage(value) {
  if (typeof value !== 'string') return null;
  const key = value.trim().toLowerCase();
  if (!key) return null;
  return LOWER_TO_CANONICAL.get(key) || null;
}

// Map a UI language to the closest Gemini Live Translate target. Regional
// variants fall back to their base (nl-BE -> nl, fr-CA -> fr). Truly
// unsupported languages pass through unchanged so the provider error
// surfaces clearly instead of mistranslating into the wrong language.
export function toGeminiTarget(code) {
  if (!code) return code;
  if (GEMINI_LIVE_TRANSLATE_SUPPORTED.has(code)) return code;
  const lower = String(code).toLowerCase();
  const aliasTargets = { tw: 'ak' };
  if (aliasTargets[lower]) return aliasTargets[lower];
  const base = String(code).split(/[-_]/)[0];
  for (const candidate of [base, base.toLowerCase()]) {
    for (const supported of GEMINI_LIVE_TRANSLATE_SUPPORTED) {
      if (supported.toLowerCase() === candidate.toLowerCase()) return supported;
    }
  }
  return code;
}

const CODE_TO_NAME = new Map(LANGUAGES.map(([code, name]) => [code.toLowerCase(), name]));
// Alias names for detection display.
for (const [alias, name] of [
  ['tl', 'Filipino'], ['iw', 'Hebrew'], ['jw', 'Javanese'], ['zh-cn', 'Chinese (Simplified)'],
  ['zh-tw', 'Chinese (Traditional)'], ['zh', 'Chinese (Simplified)'], ['ak', 'Akan'],
  ['tw', 'Twi'], ['crh', 'Crimean Tatar (Latin)'], ['sat', 'Santali (Latin)'],
]) {
  if (!CODE_TO_NAME.has(alias)) CODE_TO_NAME.set(alias, name);
}

export function getLanguageName(code) {
  if (typeof code !== 'string' || !code.trim()) return '';
  const key = code.trim().toLowerCase();
  if (CODE_TO_NAME.has(key)) return CODE_TO_NAME.get(key);
  const base = key.split(/[-_]/)[0];
  if (CODE_TO_NAME.has(base)) return CODE_TO_NAME.get(base);
  return code;
}

export function isGeminiLiveSupported(code) {
  return GEMINI_LIVE_TRANSLATE_SUPPORTED.has(code);
}
